# Generated by Django 5.1.1 on 2024-10-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='start_sympDate',
            new_name='start_sympdate',
        ),
    ]
