# Generated by Django 5.1.1 on 2024-10-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_alter_appointment_doctor_alter_appointment_patient'),
        ('appoint', '0002_rename_start_sympdate_appointment_start_sympdate'),
    ]

    operations = [
    ]
