# Generated by Django 5.1.1 on 2024-10-07 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ยาน้ำ', 'Water'), ('ยาเม็ด', 'Solid'), ('แคปซูล', 'Capsule'), ('ยาทา', 'Cream')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stockQuantity', models.IntegerField()),
                ('expiryDate', models.DateField()),
                ('instruction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriptionDetail', models.TextField(null=True)),
                ('prescriptionDate', models.DateField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoint.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribe.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribe.prescription')),
            ],
        ),
    ]
