# Generated by Django 5.1.1 on 2024-10-07 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('ด.ญ.', 'Girl'), ('ด.ช.', 'Boy'), ('นาย', 'Male'), ('น.ส.', 'Female'), ('นาง', 'Wife')])),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('personalID', models.CharField(max_length=13, unique=True)),
                ('gender', models.CharField(choices=[('ชาย', 'M'), ('หญิง', 'F')])),
                ('nationality', models.CharField(choices=[('ไทย', 'Thai'), ('อเมริกัน', 'American'), ('อังกฤษ', 'British'), ('ญี่ปุ่น', 'Japanese'), ('จีน', 'Chinese'), ('อินเดีย', 'Indian'), ('ฝรั่งเศส', 'French'), ('เยอรมัน', 'German'), ('ออสเตรเลีย', 'Australian'), ('แคนาดา', 'Canadian'), ('เกาหลี', 'Korean'), ('เวียดนาม', 'Vietnamese'), ('มาเลเซีย', 'Malaysian'), ('สิงคโปร์', 'Singaporean'), ('พม่า', 'Myanmar'), ('ลาว', 'Lao'), ('กัมพูชา', 'Cambodian'), ('ฟิลิปปินส์', 'Filipino'), ('บราซิล', 'Brazilian'), ('รัสเซีย', 'Russian')])),
                ('DOB', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'Ab Positive'), ('AB-', 'Ab Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')])),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('allergy', models.TextField(blank=True, null=True)),
                ('registrationDate', models.DateField(auto_now_add=True)),
                ('patient_image', models.ImageField(blank=True, null=True, upload_to='../static/image/')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('doctor_image', models.ImageField(upload_to='../static/image/')),
                ('shift_day', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.department')),
            ],
        ),
    ]
