# Generated by Django 5.1.1 on 2024-10-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prefix',
            field=models.CharField(default='นพ.', max_length=10),
        ),
    ]
