# Generated by Django 5.1.1 on 2024-10-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_doctor_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='personalID',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(upload_to='images/doctor/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/patient/'),
        ),
    ]
