# Generated by Django 5.1.1 on 2024-10-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_doctor_personalid_alter_doctor_doctor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/doctor/'),
        ),
    ]
