# Generated by Django 5.1.1 on 2024-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_alter_doctor_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='personalID',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
