# Generated by Django 5.1.1 on 2024-10-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_patient_patient_image'),
        ('authen', '0006_doctor_user'),
    ]

    operations = [
    ]
