# Generated by Django 5.1.1 on 2024-10-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_merge_20241009_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
