# Generated by Django 5.1.1 on 2024-10-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='personalID',
        ),
    ]
