# Generated by Django 5.1.1 on 2024-10-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0011_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
