# Generated by Django 5.1.1 on 2024-10-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0012_patient_confirmpassword_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='confirmpassword',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
