# Generated by Django 5.1.1 on 2024-10-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0015_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_image',
            field=models.ImageField(blank=True, upload_to='images/patient/'),
        ),
    ]
